{% set name = "propelauth_py" %}
{% set version = "4.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f617b45eb6746be7be9a2d6cee90dde71f8244c431285b32703e5e0468a4fd4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - httpx >=0.28.1
    - python >={{ python_min }}
    - pyjwt >=2,<3
    # upstream specifies pyjwt[crytpro]
    - cryptography >=3.4.0
    - requests

test:
  imports:
    - propelauth_py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/propelauth/propelauth-py
  summary: A python authentication library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
