{% set name = "propelauth_py" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0767ff4765db9eeb71a4097f3e92a890e6cd53422fcfa813e0ed03a8e048b5b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - httpx >=0.28.1
    - python >={{ python_min }}
    - pyjwt <3,>=2
    # upstream specifies pyjwt[crytpro]
    - cryptography >=3.4.0
    - requests 

test:
  imports:
    - propelauth_py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/propelauth/propelauth-py
  summary: A python authentication library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
