{% set name = "propelauth_py" %}
{% set version = "4.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/propelauth-py-{{ version }}.tar.gz
  sha256: ae0924b9ff2ce43324601ab17dfb4e9f85e1c2628cd9f019d58a0c1cef0372d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyjwt >=2,<3
    # upstream specifies pyjwt[crytpro]
    - cryptography >=3.4.0
    - requests

test:
  imports:
    - propelauth_py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/propelauth/propelauth-py
  summary: A python authentication library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
